### ISSUE TITLE
Install svn package to support AUTOREV in poky recipe

### ISSUE THREAD

**Issue by jjcf89** [crops/yocto-dockerfiles#23]
AUTOREV requires the svn command to work correctly on an svn repo.  Can svn be added to the containers?

**Comment by rewitt1** [comment]
> Not sure if its worth creating a test to check for git and svn installed?

It's probably unnecessary, since that's still only testing for the existence of particular binaries. oe-core will do this for all items in the **HOSTTOOLS** variable.

So If there were a test, it would be more useful to be something like, check if the fetcher works with all expected sources. But I don't think that's required for this to be merged, it would be an enhancement.

**Comment by jjcf89** [comment]
Okay

**Comment by jjcf89** [comment]
We use the crops/poky images.  Any idea how long before they are updated?

**Comment by rewitt1** [comment]
They automatically rebuild once a week, which looks like it would have been today. But I went ahead and manually caused them to rebuild.

**Comment by jjcf89** [comment]
Excellent confirmed. Thanks a bunch

**Comment by jjcf89** [comment]
```
 $ docker pull crops/poky:ubuntu-17.10
 $ docker run -it crops/poky:ubuntu-17.10 --cmd svn
Type 'svn help' for usage.
```
